### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by drauggres**

### CODE REVIEW

**Comment by manumaticx** [comment]
Wow! Thanks for this amazing PR! 👍 
I'll review asap to get this merged.

**Comment by drauggres** [comment]
Should work on SDK 6.1.1.
I've tested on 6.0.4 with this patches:
-  https://github.com/appcelerator/titanium_mobile/commit/ace13313adbc3c06b80595eee14e72d958009a79
- https://github.com/appcelerator/titanium_mobile/commit/4395b21314ba919f900040c7c58f5f4803af8ae7
- https://github.com/appcelerator/titanium_mobile/commit/2236d94da4d47bde44237eba557eca010db03f47
- https://github.com/appcelerator/titanium_mobile/commit/1d0e240b1daf3eee5de62d7de5611240649a43cf
- https://github.com/appcelerator/titanium_mobile/commit/5e6de834ecf619810c7d20c3d4d0e7948f11bb61

**Comment by m1ga** [comment]
is this implementation:
https://github.com/appcelerator/titanium_mobile/pull/9091
affected by the leak, too?

**Comment by manumaticx** [comment]
@m1ga probably yes. By the way: thanks for the pointer - I didn't know about this core integration until now! 😄

**Comment by m1ga** [comment]
A quick update: https://jira.appcelerator.org/browse/TIMOB-15910
it was merged into 6.2.0! Now there is an official drawer included

**Comment by manumaticx** [comment]
@drauggres I've just added you as a collaborator. Feel free to merge this.

**Pull request merged**
