### PR TITLE
Added abillity to change the arrow color + bug fix

### PR DESCRIPTION
**Pull request by GeraudBourdin**
Added abillity to set and change the arrow color in the create
TiDrawerLayout.createDrawer({drawerArrowIcon : true,
drawerArrowIconColor : '#A48600' });
and with  : Alloy.Globals.drawer.setDrawerArrowIconColor('#FF1414');
bug fix :
- initDrawerToggle() was fired before the setDrawerArrowIcon(), so
useArrowAnimationDrawer was allways false.
-  optionsMenu in the actionBar was broken if drawer arrow was used
(onDrawerSlide, onDrawerClosed, onDrawerOpened, onDrawerStateChanged
wasen't fired by the drawerListener.

### CODE REVIEW

**Comment by manumaticx** [comment]
Thanks a ton! You are the man! :+1:

**Comment by GeraudBourdin** [comment]
Hope all is working fine now !

**Comment by manumaticx** [comment]
I know, I should have tested it before merging but your bugfix description explained why my attempt failed so I guess this works fine. I'll test in a minute.

**Comment by GeraudBourdin** [comment]
i should have tested it better before creating a pull request.. that's my bad. I was so happy to get a working sample that i forget to test my last changes and have not fully tested with the demo app. Won't happen again !

**Comment by manumaticx** [comment]
Never mind! I really appreciate your work, great job!

**Pull request merged**
