### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by GeraudBourdin**
Update from original

### CODE REVIEW

**Comment by GeraudBourdin** [comment]
sorry mistake... just wanted to get the lasts changes from your repo to my fork repo... don't know how to delete this. (i'll create a new fork then)

**Comment by manumaticx** [comment]
No problem, see here: https://help.github.com/articles/syncing-a-fork/

**Comment by GeraudBourdin** [comment]
thanks a lot !  
By the way, i was about to test a native drawer layout implementation. have you allready tryed it ?

**Comment by manumaticx** [comment]
What do you mean? This module already uses the native drawer layout, isn't it?

**Comment by GeraudBourdin** [comment]
sorry, i meant the native burger icon

**Comment by manumaticx** [comment]
Ah yes, I started to fool around with this. Should I push my progress on a separate branch here, so you can try taking it up?

**Comment by GeraudBourdin** [comment]
I can give a try, even if i do not have much time for this :)

**Comment by manumaticx** [comment]
Yeah, same here, though I'm planning to do some refactoring soon. Just pushed the "material" branch here: https://github.com/manumaticx/Ti.DrawerLayout/commit/5683c633f98a307f35e9a91881b0a7ee338ea410

**Comment by GeraudBourdin** [comment]
thanks a lot !

**Comment by manumaticx** [comment]
I've just pushed a commit to master which replaces your workaround with the native burger icon

**Comment by GeraudBourdin** [comment]
hey ! great !  Cleanning it up is a good thing :).  Did you mannaged how to get the pane filling the height's screen ?  it seems that it needs to skip the actionbar and use a toolbar. That give me errors conflicts with titanium sdk. Did you tryed on your side ? I wander if it's possible with titanium SDK. What do you think about this kind of feature ?  useless ? do i continue digging around this idea  ?

**Comment by manumaticx** [comment]
Absolutely useful and desired feature!
At first I thought we need to wait for Titaniums implementation for the toolbar: [TIMOB-17964](https://jira.appcelerator.org/browse/TIMOB-17964) but I fooled around with this and found out that you can just use `Theme.AppCompat.Light.NoActionBar` and include the Toolbar yourself. The only problem is, this is not supported by TiCompositeLayout as parent view. Probably the same errors you are getting.

**Comment by manumaticx** [comment]
Should we continue this conversation on gitter? https://gitter.im/manumaticx/Ti.DrawerLayout

**Pull request closed without merging**
