### PR TITLE
Added a padding right and padding left value.

### PR DESCRIPTION
**Pull request by GeraudBourdin**

### CODE REVIEW

**Comment by GeraudBourdin** [comment]
ho non... i was pretty sure this will happen... I am not familliar with git. I didn't found how to update my fork repository with yours so... Do you have a solution for that ? Sorry...

**Comment by manumaticx** [comment]
No problem! I can manually merge this.

You need to add my fork as a second remote and pull (+rebase) from here first before pushing the changes to your fork.

**Comment by manumaticx** [comment]
BOOM! Niiiiice - you got it! Awesome - thanks so much! :+1:

**Comment by GeraudBourdin** [comment]
I finally understood how to get updates from your repo (hey never too old/late to learn!).
Proud that my work have been added to this project :)

**Pull request merged**
